version: '2'

services:
  data:
    image: tianon/true
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./docker/php/override.ini:/usr/local/etc/php/conf.d/99-override.ini:ro"
      - "./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "./data/db:/var/lib/mysql:rw"
      - "./data/redis:/var/lib/redis:rw"
      - "./logs/nginx:/var/log/nginx:rw"
      - "./logs/php:/var/log/php:rw"
      - "./logs/mysql:/var/log/mysql:rw"

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - data

  php:
    build: docker/php
    ports:
      - 9000:9000
    links:
      - db
      - mail
    volumes_from:
      - data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes_from:
      - data

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
